name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt install -yq intltool python3 python3-requests make python3-setuptools
          wget -c "https://gitlab.com/sulinos/devel/inary/-/archive/develop/inary-develop.tar" -O inary.tar
          tar -xf inary.tar
          cd inary-develop && sed -i "s/ffffffff/00000000/g" inary-cli && cd ..
          cd inary-develop && sudo make && cd ..
          cd inary-develop && sudo make install && cd ..
          sudo ln -s inary-cli /usr/bin/inary || true
          sudo inary ar sulin "https://osdn.net/frs/redir.php?m=dotsrc&f=storage/g/s/su/sulinos/SulinRepository/inary-index.xml.xz" -y -Dchroot  --debug
          sudo inary ur sulin -y -Dchroot  --debug
          sudo inary it baselayout --ignore-dep --ignore-safety --ignore-configure -y -Dchroot  --debug
          sudo inary it -c system.base curl -y --ignore-configure -Dchroot  --debug
          sudo chroot chroot inary rp busybox  --debug
          sudo chroot chroot inary rp baselayout  --debug
          sudo chroot chroot inary cp  --debug
          sudo mount --bind /dev chroot/dev
          sudo mount --bind /sys chroot/sys
          sudo mount --bind /proc chroot/proc
          sudo mount --bind /run chroot/run
          sudo git clone $(git remote get-url origin) chroot/build
          sudo mkdir chroot/output/
          sudo chroot chroot bash -ex /build/build.sh

      - uses: actions/upload-artifact@v2
        with:
            name: output
            path: chroot/output/*
