name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt install -yq intltool python3 python3-requests make python3-setuptools
          wget -c "https://gitlab.com/sulinos/devel/inary/-/archive/develop/inary-develop.tar" -O inary.tar
          tar -xf inary.tar
          cd inary-develop && sudo make && cd ..
          cd inary-develop && sudo make install && cd ..
          sudo ln -s inary-cli /usr/bin/inary || true
          sudo inary ar sulin "https://master.dl.sourceforge.net/project/sulinos/SulinRepository/inary-index.xml" -y -Dchroot
          sudo inary ur -y -D$chroot
          sudo inary it baselayout --ignore-dep --ignore-safety --ignore-configure -y -Dchroot
          sudo inary it -c system.base curl -y --ignore-configure -Dchroot
          sudo chroot chroot inary rp busybox
          sudo chroot chroot inary rp baselayout
          sudo chroot chroot inary cp
          sudo mount --bind /dev chroot/dev
          sudo mount --bind /sys chroot/sys
          sudo mount --bind /proc chroot/proc
          sudo mount --bind /run chroot/run
          sudo git clone $(git remote get-url origin) chroot/build
          sudo mkdir chroot/output/
          sudo chroot chroot bash /build/build.sh

      - uses: actions/upload-artifact@v2
        with:
            name: output
            path: chroot/output/*
